[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.65.2",
    "pypdf2>=3.0.1",
    "streamlit>=1.42.2",
    "twilio>=9.4.6",
]
